[workspace]
#name = "glow-wasm-workspace-test"
members = ["core", "native", "wasm"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
glow = "0.16.0"
glam = "0.30.9"
