[workspace]
#name = "glow-wasm-workspace-test"
members = ["core", "native", "wasm"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
glow = { version = "0.16.0", default-features = false }
glam = "0.30.9"
winit = "0.30.12"
